"""Plot dice-per-radii from raw CSV files (dice_radii_raw_*.csv).

Reads a folder of dice_radii_raw_<method>.csv files generated by
compute_metrics_meshes_comparison.py when run with --predictions-root (which uses
dice_per_radii.py for the underlying computation).
Groups raw (dice, radius) values by the radius buckets defined in volume_per_radii.py,
and plots violin plots: x-axis = radii buckets, one violin per method at each bucket,
legend = methods.

Usage:
	python -m seqseg.analysis.plot_dice_radii_from_raw /path/to/raw_folder
	python -m seqseg.analysis.plot_dice_radii_from_raw /path/to/raw_folder --out dice_radii.png

	# Per-case mode: one plot per case
	python -m seqseg.analysis.plot_dice_radii_from_raw /path/to/raw_folder --per-case --out-dir per_case_plots
"""

from __future__ import annotations

import argparse
import os
import re
import sys

import matplotlib.pyplot as plt
plt.rcParams['font.family'] = 'Times New Roman'
import numpy as np
import pandas as pd

try:
	from seqseg.analysis.dice_per_radii import format_bucket_label_for_display
	from seqseg.analysis.volume_per_radii import DEFAULT_RADIUS_BUCKETS
except ImportError:
	try:
		from analysis.dice_per_radii import format_bucket_label_for_display
		from analysis.volume_per_radii import DEFAULT_RADIUS_BUCKETS
	except ImportError:
		DEFAULT_RADIUS_BUCKETS = [
			(0.0, 0.2),
			(0.2, 0.4),
			(0.4, 0.6),
			(0.6, 0.8),
			(1.0, 1.2),
			(1.2, 1.6),
			(1.6, float('inf')),
		]

		def format_bucket_label_for_display(label: str, latex: bool = False) -> str:
			parts = label.split('_')
			if len(parts) >= 2:
				if parts[1] == 'inf':
					return f'[{float(parts[0]) * 10:.1f}, ∞)'
				lo, hi = float(parts[0]) * 10, float(parts[1]) * 10
				return f'[{lo:.1f}, {hi:.1f})'
			return label


MIN_COUNT_TO_SHOW = 5


def _format_method_display_name(folder: str) -> str:
	"""Map pred_folder to professional display name."""
	folder = str(folder).strip()
	if folder == 'global_pred':
		return 'EGNN (ours)'
	if folder == 'mc':
		return 'Marching Cubes'
	m = re.match(r'.*taubin.*_(\d+)_(\d+)$', folder, re.IGNORECASE)
	if m:
		a, b = m.group(1), m.group(2)
		if a.startswith('0') and len(a) >= 2:
			val = int(a) / (10 ** (len(a) - 1))
		else:
			val = int(a)
		return f'Taubin {val}/{b}'
	if 'taubin' in folder.lower():
		return 'Taubin'
	return folder


def load_raw_csv(path: str) -> pd.DataFrame:
	"""Load dice_radii_raw_*.csv with columns case, dice, radius."""
	df = pd.read_csv(path)
	for col in ['case', 'dice', 'radius']:
		if col not in df.columns:
			raise ValueError(f"CSV missing column '{col}': {path}")
	return df


def get_raw_data_by_buckets(
	df: pd.DataFrame,
	radius_buckets: list[tuple[float, float]] | None = None,
) -> list[np.ndarray]:
	"""Group raw (dice, radius) by buckets. Returns list of arrays (one per bucket).

	Excludes NaN dice values.
	"""
	if radius_buckets is None:
		radius_buckets = DEFAULT_RADIUS_BUCKETS

	arrays = []
	for r_min, r_max in radius_buckets:
		mask = (df['radius'] >= r_min) & (df['radius'] < r_max)
		vals = df.loc[mask, 'dice'].dropna()
		arrays.append(vals.values if len(vals) > 0 else np.array([]))
	return arrays


def get_bucket_labels(radius_buckets: list[tuple[float, float]] | None = None) -> list[str]:
	"""Return bucket labels matching dice_per_radii format."""
	if radius_buckets is None:
		radius_buckets = DEFAULT_RADIUS_BUCKETS
	labels = []
	for r_min, r_max in radius_buckets:
		label = f"{r_min:.1f}_{r_max:.1f}" if r_max != float('inf') else f"{r_min:.1f}_inf"
		labels.append(label)
	return labels


def _draw_violin_plot(
	ax,
	datasets: list[np.ndarray],
	positions: list[float],
	violin_colors: list,
	method_colors: np.ndarray,
	methods: list[str],
	display_labels: list[str],
	n_methods: int,
	n_buckets: int,
	ylabel: str,
	visibilities: list[bool] | None = None,
) -> None:
	"""Draw violin plot on given axes. X-axis = buckets, legend = methods.

	If visibilities given, hide violins where False.
	"""
	parts = ax.violinplot(
		datasets,
		positions=positions,
		widths=0.8,
		showmeans=True,
		showmedians=False,
		showextrema=False,
	)
	for i, pc in enumerate(parts['bodies']):
		pc.set_facecolor(violin_colors[i])
		alpha = 0.0 if (visibilities is not None and not visibilities[i]) else 0.7
		pc.set_alpha(alpha)
	# Hide mean lines for hidden violins
	if visibilities is not None and 'cmeans' in parts:
		alphas = [1.0 if visibilities[i] else 0.0 for i in range(len(visibilities))]
		parts['cmeans'].set_alpha(alphas)
	ax.set_xlabel('Radius bucket')
	ax.set_ylabel(ylabel)
	group_centers = [j * (n_methods + 1) + (n_methods - 1) / 2 for j in range(n_buckets)]
	ax.set_xticks(group_centers)
	ax.set_xticklabels(display_labels, rotation=45, ha='right')
	ax.legend(
		[plt.Rectangle((0, 0), 1, 1, fc=method_colors[j], alpha=0.7) for j in range(n_methods)],
		methods,
		loc='best',
		fontsize=9,
	)
	ax.axhline(y=1.0, color='gray', linestyle='--', linewidth=0.5, alpha=0.7)
	ax.set_xlim(-0.5, n_buckets * (n_methods + 1) - 0.5)


def plot_dice_radii_from_raw(
	raw_folder: str,
	radius_buckets: list[tuple[float, float]] | None = None,
	out_path: str | None = None,
	figsize: tuple[float, float] = (10, 6),
	per_case: bool = False,
	out_dir: str | None = None,
) -> None:
	"""Plot dice-per-radii from raw CSV files in a folder.

	X-axis: radius buckets. Each bucket has one violin per method. Legend: methods.

	Parameters
	----------
	raw_folder : str
		Path to folder containing dice_radii_raw_<method>.csv files
	radius_buckets : list of (min_r, max_r), optional
		Radius ranges (default from volume_per_radii.DEFAULT_RADIUS_BUCKETS)
	out_path : str, optional
		Path to save the figure
	figsize : tuple
		Figure size (width, height)
	per_case : bool
		If True, produce one plot per case
	out_dir : str, optional
		Output directory for per-case plots (required when per_case=True)
	"""
	if radius_buckets is None:
		radius_buckets = DEFAULT_RADIUS_BUCKETS

	# Find all dice_radii_raw_*.csv files
	pattern = 'dice_radii_raw_'
	csv_files = []
	for f in os.listdir(raw_folder):
		if f.startswith(pattern) and f.endswith('.csv'):
			method = f[len(pattern):-4]  # strip prefix and .csv
			full_path = os.path.join(raw_folder, f)
			csv_files.append((method, full_path))

	if not csv_files:
		raise FileNotFoundError(
			f"No dice_radii_raw_*.csv files found in {raw_folder}. "
			f"Expected files like dice_radii_raw_global_pred.csv"
		)

	# Load all DataFrames (method -> df)
	dfs_by_method: dict[str, pd.DataFrame] = {}
	for method, path in sorted(csv_files, key=lambda x: x[0].lower()):
		dfs_by_method[method] = load_raw_csv(path)

	# Order: MC, Taubin, EGNN
	def _sort_key(m):
		m = str(m).strip().lower()
		return (0 if m == 'mc' else 1 if 'taubin' in m else 2 if m == 'global_pred' else 3)

	methods_raw = sorted(dfs_by_method.keys(), key=_sort_key)
	methods = [_format_method_display_name(m) for m in methods_raw]
	bucket_labels = get_bucket_labels(radius_buckets)
	display_labels = [format_bucket_label_for_display(b) + ' mm radius' for b in bucket_labels]
	n_methods = len(methods)
	n_buckets = len(bucket_labels)
	method_colors = plt.cm.tab10(np.linspace(0, 1, n_methods))

	if per_case:
		# Per-case mode: one plot per case
		if out_dir is None:
			out_dir = os.path.join(raw_folder, 'per_case_plots')
		os.makedirs(out_dir, exist_ok=True)

		all_cases = set()
		for df in dfs_by_method.values():
			all_cases.update(df['case'].unique().tolist())
		all_cases = sorted(all_cases)

		for case in all_cases:
			data_by_buckets = []
			for method in methods_raw:
				df_case = dfs_by_method[method][dfs_by_method[method]['case'] == case]
				arrays = get_raw_data_by_buckets(df_case, radius_buckets)
				data_by_buckets.append(arrays)

			positions = []
			datasets = []
			violin_colors = []
			visibilities = []
			for j in range(n_buckets):
				for i in range(n_methods):
					positions.append(j * (n_methods + 1) + i)
					arr = data_by_buckets[i][j]
					n = len(arr)
					datasets.append(arr if n > 0 else np.array([0.0]))
					violin_colors.append(method_colors[i])
					visibilities.append(n >= MIN_COUNT_TO_SHOW)

			fig, ax = plt.subplots(figsize=figsize)
			_draw_violin_plot(
				ax, datasets, positions, violin_colors, method_colors,
				methods, display_labels, n_methods, n_buckets,
				'Dice coefficient',
				visibilities=visibilities,
			)
			ax.set_title(case)
			ax.set_ylim(0, 1.05)
			fig.tight_layout()
			safe_name = case.replace(os.sep, '_').replace('..', '_')
			out_path_case = os.path.join(out_dir, f'{safe_name}.png')
			fig.savefig(out_path_case, dpi=150, bbox_inches='tight')
			plt.close(fig)

		print(f'Saved {len(all_cases)} per-case plots to {out_dir}')
		return

	# Aggregate mode: one plot across all cases
	data_by_buckets = []
	for method in methods_raw:
		arrays = get_raw_data_by_buckets(dfs_by_method[method], radius_buckets)
		data_by_buckets.append(arrays)

	# Print counts and means per bucket per method (for verification)
	print('Counts per bucket (method × bucket):')
	col_w = max(8, max(len(dl) for dl in display_labels))
	header = 'Method'.ljust(20) + '  ' + '  '.join(dl.ljust(col_w) for dl in display_labels)
	print(header)
	print('-' * len(header))
	for i in range(n_methods):
		counts = [len(data_by_buckets[i][j]) for j in range(n_buckets)]
		row = methods[i].ljust(20) + '  ' + '  '.join(str(c).ljust(col_w) for c in counts)
		print(row)
	print()
	print('Mean Dice per bucket (method × bucket):')
	print(header)
	print('-' * len(header))
	for i in range(n_methods):
		means = []
		for j in range(n_buckets):
			arr = data_by_buckets[i][j]
			m = np.mean(arr) if len(arr) > 0 else float('nan')
			means.append(f'{m:.4f}' if not np.isnan(m) else '  nan')
		row = methods[i].ljust(20) + '  ' + '  '.join(m.ljust(col_w) for m in means)
		print(row)

	# Flatten for violinplot: x-axis = buckets, one violin per method at each bucket
	positions = []
	datasets = []
	violin_colors = []
	visibilities = []
	for j in range(n_buckets):
		for i in range(n_methods):
			positions.append(j * (n_methods + 1) + i)
			arr = data_by_buckets[i][j]
			n = len(arr)
			datasets.append(arr if n > 0 else np.array([0.0]))
			violin_colors.append(method_colors[i])
			visibilities.append(n >= MIN_COUNT_TO_SHOW)

	# Plot: Dice coefficient
	fig, ax = plt.subplots(figsize=figsize)
	_draw_violin_plot(
		ax, datasets, positions, violin_colors, method_colors,
		methods, display_labels, n_methods, n_buckets,
		'Dice coefficient',
		visibilities=visibilities,
	)
	ax.set_ylim(0, 1.05)
	fig.tight_layout()
	if out_path:
		fig.savefig(out_path, dpi=150, bbox_inches='tight')
		print(f'Saved figure to {out_path}')
	else:
		plt.show()


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
	p = argparse.ArgumentParser(
		description='Plot dice-per-radii from raw CSV: x-axis=buckets, violins=methods'
	)
	p.add_argument(
		'raw_folder',
		help='Folder containing dice_radii_raw_<method>.csv files',
	)
	p.add_argument(
		'--out', '-o',
		default=None,
		help='Output path for figure (default: display only)',
	)
	p.add_argument(
		'--per-case',
		action='store_true',
		help='Produce one plot per case (saved to --out-dir)',
	)
	p.add_argument(
		'--out-dir',
		default=None,
		help='Output directory for per-case plots (default: <raw_folder>/per_case_plots)',
	)
	p.add_argument(
		'--figsize',
		default='10,6',
		help='Figure size as width,height (default: 10,6)',
	)
	return p.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
	args = parse_args(argv)
	if not os.path.isdir(args.raw_folder):
		print(f'Error: Not a directory: {args.raw_folder}', file=sys.stderr)
		return 1

	try:
		figsize = tuple(float(x) for x in args.figsize.split(','))
	except ValueError:
		print(f'Error: --figsize must be width,height (e.g. 10,6)', file=sys.stderr)
		return 1

	plot_dice_radii_from_raw(
		args.raw_folder,
		out_path=args.out,
		figsize=figsize,
		per_case=getattr(args, 'per_case', False),
		out_dir=getattr(args, 'out_dir', None),
	)
	return 0


if __name__ == '__main__':
	raise SystemExit(main())
