name: Test. Tracking Vessel Segmentation

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

defaults:
  run:
    shell: bash -el {0}

jobs:
  test_scripts:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      # Install dependencies via pip
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .  # Installs the local package (seqseg)

      # Test python script
      - name: Test SeqSeg CLI
        run: |
          seqseg \
          -data_dir seqseg/tests/test_data/ \
          -config_name global_test \
          -img_ext .nii.gz \
          -outdir seqseg/tests/test_out/ \
          -start 0 \
          -stop 1 \
          -max_n_steps 3
