# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Test. Tracking Vessel Segmentation

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

defaults:
  run:
    shell: bash -el {0}

jobs:
  test_scripts:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies via conda-forge
      uses: conda-incubator/setup-miniconda@v3
      with:
          python-version: "3.10"
          channels: conda-forge
          environment-file: seqseg/tests/environment_new.yml
          channel-priority: flexible
          activate-environment: environment_new
    # Test python script
    - name: Test auto_centerline
      run: |
        conda info
        conda list
        python3 seqseg/seqseg.py \
        -data_dir seqseg/tests/test_data/ \
        -config_name global_test \
        -img_ext .nii.gz \
        -outdir seqseg/tests/test_out/ \
        -start 0 \
        -stop 1 \
        -max_n_steps 3 \
