# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Test Seg Tracing

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies via conda-forge
      uses: conda-incubator/setup-miniconda@v3
      with:
          python-version: "3.10"
          channels: conda-forge
          environment-file: environment_new.yml
          channel-priority: flexible
    # Test python script
    - name: Test with pytest
      run: |
        conda info
        conda list
        sh tests/test.sh
